# Generated by Django 2.2 on 2019-07-29 19:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PR', 'Programming'), ('SP', 'Sports'), ('HE', 'Health'), ('MU', 'Music'), ('LI', 'Life'), ('TR', 'Travel')], default='PR', max_length=2)),
                ('title', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('claps', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
